spring:
  datasource:
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USERNAME:guest}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true

logging:
  level:
    sql: trace