spring:
  datasource:
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    password: ${RABBIT_PASSWORD:guest}
    username: ${RABBIT_USERNAME:guest}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true

spring-doc:
  swagger-ui:
    operationsSorter: method
  api-docs:
    path: /api-docs/subscription-service

logging:
  level:
    sql: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"